
voorportaal_pad: Z:\magazijn\voorportaal
magazijn_pad: Z:\magazijn
csvbestandsnaam1: "kenmerken_bestandensnaam1.csv"
csvbestandsnaam2: "kenmerken_bestandensnaam2.csv"
archiefmappen: "N:" # Begin van het (oude) mappen archief
#archiefmappen: N:\programmatuur # test
csv_container:            # definitie CSV-record
  -    # bestand_kenmerken
    - ""
    - ""

  -    # email_kenmerken
    - ""
    - ""
    - ""
    - ""

  -    # archief_kenmerken
    - ""
    - ""
    - ""
    - ""
    - ""


logging:
  level: INFO
  logbestand: Z:\magazijn\voorportaal\archielog.log
  format: '%(asctime)s [%(levelname)s] %(name)s - %(message)s'
  max_bytes: 1048576
  backups: 5

documenten:
- .csv
- .docx
- .doc
- .eml
- .html
- .json
- .mht
- .msg
- .pdf
- .odt
- .txt
- .zip
- .xlr
- xlsx


inboxen:
- Postvak IN
- Archiveren


#xxxxxxxxARCHIVEER
kenmerken:
- Naam
- Datum
- Bedrag
- Organisatie
- Opmerking

#Verander die lijst naar wat jij nodig hebt. Een veld met de naam "Opmerking", "Notities" of "Beschrijving" krijgt automatisch een groter tekstvak.




